POST http://piscesinsectprodbackend-dev.ap-southeast-2.elasticbeanstalk.com/add-data
Content-Type: application/json

{
  "RoomNumber": 2,
  "Date": "2024-08-09",
  "FoodType": "1 Scoop",
  "WaterType": "Sponge",
  "Tubs": 5,
  "Week": 2,
  "Stock": 300
}
