POST https://cognito-idp.ap-southeast-2.amazonaws.com/
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.SignUp

{
  "ClientId": "fsklgrvsppomao3savu9397n5",
  "Username": "testuser",
  "Password": "TestPassword123!",
  "UserAttributes": [
    {
      "Name": "email",
      "Value": "testuser@example.com"
    }
  ],
  "SecretHash": "<generated-secret-hash>"
}